#pragma once

#define AUDIO_SAMPLERATE 48000
#define AUDIO_BUF_SIZE 2048
#define AUDIO_BUF_SIZE_STEREO AUDIO_BUF_SIZE * 2


#define VISIBLE_X 256
#define VISIBLE_Y 192
#define START_X 4
#define START_Y 0
#define VIDEO_WIDTH 263
#define VIDEO_HEIGHT 193